package ua.lviv.bas.cinema.domain.audit;

public enum AuditAction {

	CREATED, UPDATED, DELETED, REGISTER, PASSWORD_CHANGED, PASSWORD_RESET_REQUESTED, PASSWORD_RESET_COMPLETED,
	EMAIL_CHANGE_REQUESTED, ROLE_CHANGED, STATUS_CHANGED, VERIFICATION_CHANGED, CANCELLED, CONFIRMED, SUCCESS, FAILED,
	REFUND, RETRY, REJECTED, REACTIVATED, VALIDATED, CLAIMED, POINTS_ADDED, POINTS_SPENT, POINTS_ACCRUED,
	POINTS_REFUNDED, TOGGLE_STATUS, RESET_TO_DEFAULTS
}