package ua.lviv.bas.cinema.domain.audit;

public enum AuditAction {

	// CRUD операції
	CREATED, UPDATED, DELETED,

	// Користувачі
	REGISTER, PASSWORD_CHANGED, PASSWORD_RESET_REQUESTED, PASSWORD_RESET_COMPLETED, EMAIL_CHANGE_REQUESTED,
	ROLE_CHANGED, STATUS_CHANGED, VERIFICATION_CHANGED,

	// Бронювання та оплата
	CANCELLED, CONFIRMED, SUCCESS, FAILED, REFUND, RETRY, REJECTED, REACTIVATED,

	// Квитки
	VALIDATED,

	// Промоції
	CLAIMED,

	// Бонуси
	POINTS_ADDED, POINTS_SPENT, POINTS_ACCRUED, POINTS_REFUNDED,

	// Адміністрування
	TOGGLE_STATUS, RESET_TO_DEFAULTS
}