spring:
    config:
        activate:
            on-profile: local
    datasource:
        url: jdbc:postgresql://localhost:5433/cinema_db
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                use_sql_comments: true

scheduler:
    birthday-bonus:
        cron: "0 */5 * * * *"
    email-token:
        cleanup-expired-cron: "0 */5 * * * *"
        cleanup-confirmed-cron: "0 */5 * * * *"
    movie-status:
        cron: "0 */5 * * * *"
    session-status:
        cron: "0 */5 * * * *"
    booking:
        expiration-interval: 300000
        cleanup-cron: "0 */5 * * * *"
        reminder-cron: "0 */5 * * * *"
    payment:
        expiration-interval: 300000
        cleanup-cron: "0 */5 * * * *"
        daily-stats: "0 */5 * * * *"
    ticket:
        mark-as-used: 300000
        cleanup-cron: "0 */5 * * * *"
        daily-stats: "0 */5 * * * *"
        upcoming-reminder: "0 */5 * * * *"
    seat-reservation:
        expiration-interval: 60000

logging:
    level:
        org.springframework.security: DEBUG
        org.springframework.web: DEBUG
        org.springframework.web.cors: DEBUG
        ua.lviv.bas.cinema.config.security: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.orm.jdbc.bind: TRACE