spring:
    config:
        activate:
            on-profile: local
    datasource:
        url: jdbc:postgresql://localhost:5433/cinema_db

scheduler:
    birthday-bonus:
        cron: "0 */5 * * * *"
    email-token:
        cleanup-expired-cron: "0 */5 * * * *"
        cleanup-confirmed-cron: "0 */5 * * * *"
    movie-status:
        cron: "0 */5 * * * *"
    session-status:
        cron: "0 */5 * * * *"
    booking:
        expiration-interval: 300000
        cleanup-cron: "0 */5 * * * *"
        reminder-cron: "0 */5 * * * *"
    payment:
        expiration-interval: 300000
        cleanup-cron: "0 */5 * * * *"
        daily-stats: "0 */5 * * * *"
