spring:
    application:
        name: cinema
    config:
        import: optional:file:.env.local[.properties]
    datasource:
        url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:cinema_db}
        username: ${DB_USER:cinema}
        password: ${DB_PASSWORD:}
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: 5
            connection-timeout: 30000
    jpa:
        hibernate:
            ddl-auto: validate
        open-in-view: false
        properties:
            hibernate:
                "[format_sql]": ${SHOW_SQL:true}
            jakarta:
                persistence:
                    schema-generation:
                        scripts:
                            action: none
        show-sql: ${SHOW_SQL:true}
    flyway:
        enabled: true
        baseline-on-migrate: true
        locations: classpath:/db/migration
        validate-on-migrate: true
        validate-migration-naming: true
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${EMAIL_USERNAME:}
        password: ${EMAIL_PASSWORD:}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                    connectiontimeout: 5000
                    timeout: 5000
                    writetimeout: 5000
    task:
        execution:
            pool:
                core-size: 3
                max-size: 5
                queue-capacity: 50
            thread-name-prefix: "scheduler-"

app:
    jwt:
        secret: ${JWT_SECRET:local_fallback_secret_key_for_dev_only}
        expiration: 86400000
    ticket:
        qr:
            size: 200
        base-url: ${APP_BASE_URL:http://localhost:8080}
    company:
        name: "Bas Cinema"
    frontend:
        url: ${FRONTEND_URL:http://localhost:5173}
    email:
        from: ${EMAIL_FROM:noreply@bascinema.com}
    qr:
        code:
            size: 200
            margin: 1
            format: PNG

payment:
    liqpay:
        public_key: ${LIQPAY_PUBLIC_KEY}
        private_key: ${LIQPAY_PRIVATE_KEY}
        sandbox_mode: ${LIQPAY_SANDBOX_MODE:true}
        currency: ${LIQPAY_CURRENCY:UAH}
        language: ${LIQPAY_LANGUAGE:uk}
        server_url: ${PAYMENT_LIQPAY_SERVER_URL:https://www.liqpay.ua/api/3/checkout}
        callback_url: ${PAYMENT_LIQPAY_CALLBACK_URL:http://localhost:8080/api/payments/callback}
        result_url: ${PAYMENT_LIQPAY_RESULT_URL:http://localhost:3000/payment/result}
