package ua.lviv.bas.cinema.domain.enums;

public enum BonusTransactionType {
	WELCOME_BONUS, BIRTHDAY_BONUS, PURCHASE_BONUS, PURCHASE_WRITE_OFF, REFUND_DEDUCTION, PROMOTION_BONUS,
	MANUAL_CORRECTION, EXPIRATION_DEDUCTION
}